### ISSUE TITLE
LocationNotFoundException (Location with the name "GMT" doesn't exist)

### ISSUE THREAD

**Issue by armandojimenez** [srawlins/timezone#92] opened 2021-02-24 15:37 UTC
How do I deal with this? I'm getting this on an Android Emulator

LocationNotFoundException (Location with the name "GMT" doesn't exist)

**Comment by mariamalbarghouti** [comment] 2021-03-18 06:25
did you solve this issue?

**Comment by zjamshidi** [comment] 2021-03-23 13:46
same isssue

**Comment by armandojimenez** [comment] 2021-03-23 13:53
Still with the same issue, I added a try/catch and assign "Accra/Africa" if an error occurs

**Comment by mariamalbarghouti** [comment] 2021-03-23 14:46
i need to make it reach Africa too

**Comment by armandojimenez** [comment] 2021-03-23 15:28
I use this, works good, but this error only occurs to me in Apple Sillicon Android Emulator

`
static Future<void> _configureLocalTimeZone() async {
    tz.initializeTimeZones();
    final String timeZoneName = await FlutterNativeTimezone.getLocalTimezone();
    Logger.log('Timezone: $timeZoneName', className: '$AppConfig');
    try {
      tz.setLocalLocation(tz.getLocation(timeZoneName));
    } catch (_) {
      // Failed to get timezone or device is GMT or UTC, assign generic timezone
      const String fallback = 'Africa/Accra';
      Logger.log('Could not get a legit timezone, setting as $fallback',
          className: '$AppConfig');
      tz.setLocalLocation(tz.getLocation(fallback));
    }
  }



`

**Comment by mariamalbarghouti** [comment] 2021-04-14 06:02
> 
> 
> I use this, works good, but this error only occurs to me in Apple Sillicon Android Emulator
> 
> `
> static Future _configureLocalTimeZone() async { tz.initializeTimeZones(); final String timeZoneName = await FlutterNativeTimezone.getLocalTimezone(); Logger.log('Timezone: $timeZoneName', className: '$AppConfig'); try { tz.setLocalLocation(tz.getLocation(timeZoneName)); } catch (_) {
> // Failed to get timezone or device is GMT or UTC, assign generic timezone
> const String fallback = 'Africa/Accra';
> Logger.log('Could not get a legit timezone, setting as $fallback',
> className: '$AppConfig');
> tz.setLocalLocation(tz.getLocation(fallback));
> }
> }
> 
> `

is this problem occurs only  when the user lives in afirca ?

**Comment by Wolfteam** [comment] 2021-06-05 17:47
Hiho, I'm getting some crashes with this, in my case I get these:

Location with the name "Asia/Yangon" doesn't exist

Location with the name "America/Buenos_Aires" doesn't exist

Location with the name "Europe/Saratov" doesn't exist

Location with the name "Asia/Calcutta" doesn't exist

Location with the name "GMT" doesn't exist

Location with the name "Etc/GMT+3" doesn't exist

**Comment by stvdbac** [comment] 2021-07-26 06:19
did you try using:
`import 'package:timezone/data/latest_all.dart' as tz;`
in stead of
`import 'package:timezone/data/latest.dart' as tz;`

**Comment by levitanong** [comment] 2022-03-28 04:01
With `latest_all`, "Asia/Yangon", "America/Buenos_Aires", "Etc/GMT" etc... work fine.

But "GMT" still throws for me. "Etc/GMT" seems like a good enough workaround in a try/catch.

**Comment by missbeins** [comment] 2022-06-09 18:04
> With `latest_all`, "Asia/Yangon", "America/Buenos_Aires", "Etc/GMT" etc... work fine.
> 
> But "GMT" still throws for me. "Etc/GMT" seems like a good enough workaround in a try/catch.

can i see your try/catch code? i am also getting "[LocationNotFoundException (Location with the name "GMT" doesn't exist)]" error on my flutter app

**Comment by srawlins** [comment] 2022-10-26 18:00
Duplicate of https://github.com/srawlins/timezone/issues/80; we need to add recognized aliases, like `GMT`.

**Closed by srawlins** 2022-10-26 18:00 UTC

**Comment by souza99** [comment] 2023-07-25 22:00
i'm having this problem but. it's work :

  Future<void> _configureLocalTimeZone() async {
    tz.initializeTimeZones();
    final String timeZone = await FlutterNativeTimezone.getLocalTimezone();
    tz.setLocalLocation(tz.getLocation(timeZone));
  }
