### ISSUE TITLE
not found "dart.html"

### ISSUE THREAD

**Issue by DuyStifler** [srawlins/timezone#38] opened 2019-09-01 15:10 UTC
I run "getLocation" method in both dart console-full and flutter, but I alway get error "not found dart.hrml".
How can fix it? Thanks

**Comment by srawlins** [comment] 2019-09-09 21:22
Please post the code you are trying. I need a stack trace or something. The error in your summary is different from the error in the title.

**Comment by lukelima** [comment] 2019-09-18 03:45
> I run "getLocation" method in both dart console-full and flutter, but I alway get error "not found dart.hrml".
> How can fix it? Thanks

hey dude! Have you copied the error message ? If so, you typed "hrml" instead of html

**Comment by wpietri** [comment] 2019-09-23 18:26
I just had this problem and it took me a while to run down. I was already using the timezone package happily elsewhere in my app. I extracted a bunch of widget code into its own file. Android Studio noticed that TZDateTime was not defined and offered to import it for me. I then went on with my cleanup, but when I did a full rebuild, I got this:

```
Error reading dependency file /home/william/projects/tfproto/build/app/intermediates/flutter/debug/android-arm/snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1
Error reading dependency file /home/william/projects/tfproto/build/app/intermediates/flutter/debug/android-arm/snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1
                                                                        
Compiler message:                                                       
../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/timezone-0.5.5/lib/browser.dart:17:8: Error: Not found: 'dart:html'
import 'dart:html';                                                     
       ^                                                                
../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/browser_client.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html';                                                     
       ^                                                                
../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/browser_client.dart:97:25: Error: Type 'HttpRequest' not found.
  void _openHttpRequest(HttpRequest request, String method, String url, 
                        ^^^^^^^^^^^                                     
../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/browser_client.dart:32:25: Error: 'HttpRequest' isn't a type.
  final _xhrs = new Set<HttpRequest>();                                 
                        ^^^^^^^^^^^                                     
../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/timezone-0.5.5/lib/browser.dart:48:10: Error: Getter not found: 'HttpRequest'.
  return HttpRequest.request(path,                                      
         ^^^^^^^^^^^                                                    
```

This appeared to have no relation to anything I was doing, and since I had made a few pubspec changes and had recently upgraded flutter, it took me quite a while to realize that the real problem was that AndroidStudio had added this for my import line: `import 'package:timezone/browser.dart';`

I would love to see a better error message here. As a humble app developer trying to learn Flutter, I had no idea just trying to use a time zone might drag me out into the deep waters of Flutter Web, which I did not know existed.

**Comment by srawlins** [comment] 2019-09-23 20:12
Ouch. This is no good.

So you had file `a.dart` working with `initializeTimeZone`, imported via `import 'package:timezone/standalone.dart'`. When you move the `initializeTimeZone` line to `b.dart`, Android Studio tries to auto-import `'package:timezone/browser.dart'`???

I wish I could help, but this sounds like a bug in AndroidStudio, or perhaps analysis_server.

**Comment by wpietri** [comment] 2019-09-24 04:55
I think in this case it asked me what I wanted, but I accepted the default import without looking. When I check now, it offers three options. They are in alphabetical order, making `browser` the default.

![Selection_885](https://user-images.githubusercontent.com/83547/65481912-17d18a80-de4c-11e9-93c3-82b9f3348789.png)

99% of the time the first option is the correct one, as libraries with multiple versions of the same object name are not very common. So I imagine most people don't look too hard.

The error message I gave comes from the command-line build, so this isn't strictly an Android Studio problem; it'll happen to anybody who imports the wrong slice of the library. But the problem is certainly easier to trigger in anything that helps with imports.

**Comment by Engel-Rich** [comment] 2022-09-23 16:57
instead of `import 'package:timezone/browser.dart';` use `import 'package:timezone/timezone.dart';`

**Comment by srawlins** [comment] 2022-10-26 17:31
As there's nothing to be done in this package, I'm closing this issue.

**Closed by srawlins** 2022-10-26 17:31 UTC
Labels: blocked

**Comment by sondevelopervn** [comment] 2022-12-14 06:25
> instead of `import 'package:timezone/browser.dart';` use `import 'package:timezone/timezone.dart';`

Thank you!

**Comment by SirioRigel** [comment] 2023-02-14 19:08
Didn't want to necropost but for wathever reason, Android Studio autoImported this package:  `import 'package:timezone/browser.dart'; ` which caused this error:

```
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/timezone-0.9.1/lib/browser.dart:45:10: Error: Undefined name 'HttpRequest'.
  return HttpRequest.request(path,
         ^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159
```

This can be easly avoided by just importing this package instead: `import 'package:timezone/standalone.dart';`.
Since I was trying to build for a mobile application, the import `dart.html` in the first mentioned import will result as a build error because it only targets a web build.
Took me a while to figure out and I hope it will help people in the future.

**Comment by Artein** [comment] 2023-04-29 17:33
Same to me. Just faced that issue and it spend 1 hour to find out this solution. It must fixed somehow
