### ISSUE TITLE
Compilation & Runtime error with Flutter App

### ISSUE THREAD

**Issue by cjarman** [srawlins/timezone#13] opened 2018-06-10 04:18 UTC
**Env:**
Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (4 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E199, locale en-AU)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
[✓] VS Code (version 1.24.0)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Compilation error as follows:**
Launching lib/main.dart on iPhone X in debug mode...
compiler message: file:///Users/craigjarman/.pub-cache/hosted/pub.dartlang.org/timezone-0.4.3/lib/src/date_time.dart:321:34: Error: The parameter 'other' of the method 'TZDateTime::difference' has type timezone.src.date_time::TZDateTime, which does not match the corresponding type in the overridden method (dart.core::DateTime).
compiler message: Change to a supertype of dart.core::DateTime (or, for a covariant parameter, a subtype).
compiler message:   Duration difference(TZDateTime other) {
compiler message:                                  ^
compiler message: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/runtime/lib/date_patch.dart: Context: This is the overriden method ('difference').
compiler message: file:///Users/.pub-cache/hosted/pub.dartlang.org/timezone-0.4.3/lib/src/date_time.dart:386:36: Error: The parameter 'other' of the method 'TZDateTime::isAtSameMomentAs' has type timezone.src.date_time::TZDateTime, which does not match the corresponding type in the overridden method (dart.core::DateTime).
compiler message: Change to a supertype of dart.core::DateTime (or, for a covariant parameter, a subtype).
compiler message:   bool isAtSameMomentAs(TZDateTime other) {
compiler message:                                    ^
compiler message: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/core/date_time.dart: Context: This is the overriden method ('isAtSameMomentAs').
compiler message: file:///Users/.pub-cache/hosted/pub.dartlang.org/timezone-0.4.3/lib/src/date_time.dart:396:28: Error: The parameter 'other' of the method 'TZDateTime::compareTo' has type timezone.src.date_time::TZDateTime, which does not match the corresponding type in the overridden method (dart.core::DateTime).
compiler message: Change to a supertype of dart.core::DateTime (or, for a covariant parameter, a subtype).
compiler message:   int compareTo(TZDateTime other) => millisecondsSinceEpoch.compareTo(other.millisecondsSinceEpoch);
compiler message:                            ^
compiler message: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/core/date_time.dart: Context: This is the overriden method ('compareTo').
compiler message: file:///Users/.pub-cache/hosted/pub.dartlang.org/timezone-0.4.3/lib/src/date_time.dart:11:7: Error: The non-abstract class 'TZDateTime' is missing implementations for these members:
compiler message:   'microsecondsSinceEpoch', 'microsecond'.
compiler message: Try to either
compiler message:  - provide an implementation,
compiler message:  - inherit an implementation from a superclass or mixin,
compiler message:  - mark the class as abstract, or
compiler message:  - provide a 'noSuchMethod' implementation.
compiler message: 
compiler message: class TZDateTime implements DateTime {
compiler message:       ^^^^^^^^^^
compiler message: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/runtime/lib/date_patch.dart: Context: 'microsecondsSinceEpoch' is defined here.
compiler message: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/runtime/lib/date_patch.dart: Context: 'microsecond' is defined here.
Compiler failed on lib/main.dart
Error launching application on iPhone X.

**Comment by cjarman** [comment] 2018-06-10 04:31
I see this is resolved with the latest Dev release.

New runtime error is "Unsupported operation: Isolate.resolvePackageUri".

**Comment by srawlins** [comment] 2018-06-10 22:19
More or less a duplicate of #9 . TL;DR Known Flutter issue; workaround in #9.

**Closed by srawlins** 2018-06-10 22:19 UTC
